stages:
  - docker-base-image
  - test
  - export
  - docker-image

variables:
  DOCKER_TAG: latest

build-docker-base-image:
  stage: docker-base-image
  tags:
    - runnersv2-shell
  only:
    changes:
      - Dockerfile-base
      - config/*
      - src/requirements.txt
  before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  script:
    - docker build -f Dockerfile-base -t productize/kicad-automation-base:$DOCKER_TAG .
    - docker push productize/kicad-automation-base

test-erc:
  image: productize/kicad-automation-base
  tags:
    - docker
  script:
    - ./src/eeschema/schematic.py run_erc ./test-projects/good-project/good-project.sch output
  stage: test
  artifacts:
    paths:
      - output
    expire_in: 1 day

test-erc-warning:
  image: productize/kicad-automation-base
  tags:
    - runner-v11.2
  script:
    - ./src/eeschema/schematic.py run_erc -x ./test-projects/warning-project/warning-project.sch output
  stage: test
  artifacts:
    reports:
      junit: output/junit.xml
    expire_in: 1 day

export-schematic-pdf:
  image: productize/kicad-automation-base
  tags:
    - docker
  script:
    - ./src/eeschema/schematic.py export -a -f pdf ./test-projects/good-project/good-project.sch output
  stage: export
  artifacts:
    paths:
      - output
    expire_in: 1 day

test-drc:
  image: productize/kicad-automation-base
  tags:
    - docker
  script:
    - ./src/pcbnew_automation/run_drc.py ./test-projects/good-project/good-project.kicad_pcb output
  stage: test

export-layout-gerbers:
  image: productize/kicad-automation-base
  tags:
    - docker
  script:
    - ./src/pcbnew_automation/plot.py ./test-projects/good-project/good-project.kicad_pcb plot
  stage: export
  artifacts:
    paths:
      - plot
    expire_in: 1 day

export-layout-pdf:
  image: productize/kicad-automation-base
  tags:
    - docker
  script:
    - ./src/pcbnew_automation/plot.py -f pdf ./test-projects/good-project/good-project.kicad_pcb plot
    - ./src/pcbnew_automation/plot.py -f pdf ./test-projects/good-project/good-project.kicad_pcb plot Dwgs.User
  stage: export
  artifacts:
    paths:
      - plot
    expire_in: 1 day

build-docker-image:
  stage: docker-image
  tags:
    - runnersv2-shell
  before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  script:
    - docker build -t productize/kicad-automation-scripts --build-arg base_tag=$DOCKER_TAG .
    - docker push productize/kicad-automation-scripts
