stages:
  - test
  - export

test-erc:
  image: productize/kicad-automation-scripts
  tags:
  - docker
  script:
    - ./eeschema/schematic.py run_erc ./test-projects/good-project/good-project.sch output
  stage: test
  artifacts:
    paths:
      - output
    expire_in: 1 day

export-schematic-pdf:
  image: productize/kicad-automation-scripts
  tags:
  - docker
  script:
    - ./eeschema/schematic.py export -a -f pdf ./test-projects/good-project/good-project.sch output
  stage: export
