stages:
  - test
  - export

test-erc:
  image: productize/kicad-automation-scripts:test
  tags:
  - docker
  script:
    - python -m kicad-automation.eeschema.schematic run_erc ./test-projects/kicad5/good-project-true/good-project.sch output
  stage: test
  artifacts:
    paths:
      - output
    expire_in: 1 day

export-schematic-pdf:
  image: productize/kicad-automation-scripts:test
  tags:
  - docker
  script:
    - python -m kicad-automation.eeschema.schematic export -a -f pdf ./test-projects/kicad5/good-project-true/good-project.sch output
  stage: export
