stages:
  - test
  - export
  - release

test-erc:
  image: productize/kicad-automation-scripts
  tags:
    - docker
  script:
    - ./eeschema/schematic.py run_erc ./test-projects/good-project/good-project.sch output
  stage: test
  artifacts:
    paths:
      - output
    expire_in: 1 day

export-schematic-pdf:
  image: productize/kicad-automation-scripts
  tags:
    - docker
  script:
    - ./eeschema/schematic.py export -a -f pdf ./test-projects/good-project/good-project.sch output
  stage: export
  artifacts:
    paths:
      - output
    expire_in: 1 day

test-drc:
  image: productize/kicad-automation-scripts
  tags:
    - docker
  script:
    - ./pcbnew_scripts/run_drc.py ./test-projects/good-project/good-project.kicad_pcb output
  stage: test

export-layout-svg:
  image: productize/kicad-automation-scripts
  tags:
    - docker
  script:
    - ./pcbnew_scripts/generate_svg.py ./test-projects/good-project/good-project.kicad_pcb
  stage: export
  artifacts:
    paths:
      - build
    expire_in: 1 day

create-release:
    stage: release
    tags:
      - docker
    image: appropriate/curl
    variables:
      CI_DEBUG_TRACE: "true"
    script:
      - |
        curl -X POST --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --data '{"name": "test-release", "tag_name": "testing", "ref": "$CI_COMMIT_SHA", "description": "Testing releases", "assets": {"links": [{"name": "build", "url": "build"}]}}' $CI_API_V4_API_URL/projects/$CI_PROJECT_ID/releases
    when: manual
